import { Button, Grid, Paper, Text } from "@mantine/core";
import Head from "next/head";
import { useState } from "react";
import NavBar from "../../components/NavBar/UI/Navbar";
import { Media } from "../Media";
import dayjs from "dayjs";
import Footer from "../../components/NavBar/UI/Footer";
import { MdArrowForwardIos } from "react-icons/md";
export default function Aktuality() {
  const [data, setData] = useState([
    {
      datum: dayjs(),
      nadpis: "Aktualita 256",
      text: "Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Integer in sapien. Quisque tincidunt scelerisque libero. Duis viverra diam non justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Suspendisse sagittis ultrices augue.",
    },
    {
      datum: dayjs(),
      nadpis: "Aktualita 256",
      text: "Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Integer in sapien. Quisque tincidunt scelerisque libero. Duis viverra diam non justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Suspendisse sagittis ultrices augue.",
    },
    {
      datum: dayjs(),
      nadpis: "Aktualita 256",
      text: "Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Integer in sapien. Quisque tincidunt scelerisque libero. Duis viverra diam non justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Suspendisse sagittis ultrices augue.",
    },
    {
      datum: dayjs(),
      nadpis: "Aktualita 256",
      text: "Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Integer in sapien. Quisque tincidunt scelerisque libero. Duis viverra diam non justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Suspendisse sagittis ultrices augue.",
    },
  ]);
  return (
    <>
      <Head>
        <title>Aktuality | Vinarštví Badinovi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <Media between={["zero", "mobile"]}>
        <div>
          <section
            style={{
              width: "100%",
              height: "50vh",
              backgroundImage: 'url("images/grape.jpg")',
              backgroundSize: "cover",
              backgroundPosition: "center",
              display: "flex",
              flexDirection: "column",
              minHeight: "fit-content",
            }}
          >
            <NavBar backgroundColor="#fff" />
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                height: "100%",
              }}
            >
              <Text
                size="xl"
                sx={{ color: "white", fontSize: "13vw", textAlign: "center" }}
              >
                Aktuality
              </Text>
            </div>
          </section>
          <section>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "5vh",
                padding: "1vh 2vw 0 2vw",
              }}
            >
              {data &&
                data.map((novinka) => {
                  return (
                    <div>
                      <Paper shadow="xl" p={10} sx={{display: "flex", flexDirection: "row"}}>
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "5%",
                          }}
                        >
                          <div
                            style={{
                              display: "flex",
                              alignItems: "center",
                              backgroundColor: "#A54E4E",
                              color: "#fff",
                              height: "100%",
                              flexDirection: "column",
                              padding: "2% 5% ",
                              borderRadius: "3px",
                            }}
                          >
                            <Text
                              size="xl"
                              sx={{ fontWeight: "700", fontSize: "1.5rem" }}
                            >
                              {dayjs(novinka.datum, "D-M-YYYY").format("D")}
                            </Text>
                            <div style={{ display: "flex" }}>
                              <Text
                                size="xl"
                                sx={{ fontWeight: "400", fontSize: "1rem" }}
                              >
                                {dayjs(novinka.datum).format("M")}
                              </Text>
                              <Text
                                size="xl"
                                sx={{ fontWeight: "400", fontSize: "1rem" }}
                              >
                                {dayjs(novinka.datum).format("YYYY")}
                              </Text>
                            </div>
                          </div>
                          <Text
                            size="xl"
                            sx={{ fontWeight: "400", fontSize: "2rem" }}
                          >
                            {novinka.nadpis}
                          </Text>
                        </div>
                        <Text>{novinka.text}</Text>
                        <Button
                          sx={{
                            backgroundColor: "rgb(147, 37, 37)",
                            aspectRatio: 1,
                            textAlign: "right",
                            aspectRatio: 1,
                            marginTop: "3vh",
                            alignSelf: "flex-end",
                          }}
                          color="red"
                        >
                         
                          <MdArrowForwardIos />
                        </Button>
                      </Paper>
                    </div>
                  );
                })}
            </div>
          </section>
        </div>
      </Media>
      <Media between={["mobile", "tablet"]}>
      <div>
          <section
            style={{
              width: "100%",
              height: "50vh",
              backgroundImage: 'url("images/grape.jpg")',
              backgroundSize: "cover",
              backgroundPosition: "center",
              display: "flex",
              flexDirection: "column",
              minHeight: "fit-content",
            }}
          >
            <NavBar backgroundColor="#fff" />
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                height: "100%",
              }}
            >
              <Text
                size="xl"
                sx={{ color: "white", fontSize: "13vw", textAlign: "center" }}
              >
                Aktuality
              </Text>
            </div>
          </section>
          <section>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "5vh",
                padding: "1vh 2vw 0 2vw",
              }}
            >
            <Grid>
              {data &&
                data.map((novinka) => {
                  return (
                    
                     <Grid.Col span={4}>
                     <Paper shadow="xl" p={10} sx={{display: "flex", flexDirection: "column"}}>
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "5%",
                          }}
                        >
                          <div
                            style={{
                              display: "flex",
                              alignItems: "center",
                              backgroundColor: "#A54E4E",
                              color: "#fff",
                              height: "100%",
                              flexDirection: "column",
                              padding: "2% 5% ",
                              borderRadius: "3px",
                            }}
                          >
                            <Text
                              size="xl"
                              sx={{ fontWeight: "700", fontSize: "1.5rem" }}
                            >
                              {dayjs(novinka.datum, "D-M-YYYY").format("D")}
                            </Text>
                            <div style={{ display: "flex" }}>
                              <Text
                                size="xl"
                                sx={{ fontWeight: "400", fontSize: "1rem" }}
                              >
                                {dayjs(novinka.datum).format("M")}
                              </Text>
                              <Text
                                size="xl"
                                sx={{ fontWeight: "400", fontSize: "1rem" }}
                              >
                                {dayjs(novinka.datum).format("YYYY")}
                              </Text>
                            </div>
                          </div>
                          <Text
                            size="xl"
                            sx={{ fontWeight: "400", fontSize: "2rem" }}
                          >
                            {novinka.nadpis}
                          </Text>
                        </div>
                        <Text>{novinka.text}</Text>
                        <Button
                          sx={{
                            backgroundColor: "rgb(147, 37, 37)",
                            aspectRatio: 1,
                            textAlign: "right",
                            aspectRatio: 1,
                            marginTop: "3vh",
                            alignSelf: "flex-end",
                          }}
                          color="red"
                        >
                         
                          <MdArrowForwardIos />
                        </Button>
                      </Paper>
                     </Grid.Col>
                   
                  );
                })}
                </Grid>
            </div>
          </section>
        </div>
      </Media>
      <Media between={["tablet", "laptop"]}>C</Media>
      <Footer />
    </>
  );
}
