import { Button, Text } from "@mantine/core";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/NavBar/UI/Footer";
import NavBar from "../components/NavBar/UI/Navbar";
import styles from "./index.module.css";
import { Media } from "./Media";
import { MdArrowForwardIos } from "react-icons/md";
import Link from "next/link";
import OnasLaptop from "../components/NavBar/forIndex/o-nas/OnasLaptop";
import SortimentLaptop from "../components/NavBar/forIndex/sortiment/sortimentLaptop";
import AktualityLaptop from "../components/NavBar/forIndex/aktuality/AktualityLaptop";
import KdeLaptop from "../components/NavBar/forIndex/Kde/KdeLaptop";
import OnasMobile from "../components/NavBar/forIndex/o-nas/OnasMobile";
import SortimentMobile from "../components/NavBar/forIndex/sortiment/sortimentMobile";
import AktualityMobile from "../components/NavBar/forIndex/aktuality/AktualityMobile";
import KdeMobile from "../components/NavBar/forIndex/Kde/KdeMobile";
export default function Home() {
  return (
    <>
      <Head>
        <title>Vinarštví Badinovi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <Media between={["tablet", "laptop"]}>
        <div className={styles.main_laptop}>
          <section className={styles.firstSection_laptop}>
            <NavBar backgroundColor="transparent" />
            <Text
              size="xl"
              sx={{ color: "#C4C4C4", fontSize: "6.5vw", marginTop: "10%" }}
            >
              Vinařství Badinovi
            </Text>
            <div
              style={{
                display: "flex",
                gap: "10%",
                justifyContent: "center",
                marginTop: "10%",
                paddingBottom: "5%",
              }}
            >
              <Link href="/sortiment">
              <Button
                variant="outline"
                size="xl"
                radius="sm"
                sx={{
                  color: "white",
                  borderColor: "white",
                  width: "12vw",
                  minWidth: "fit-content",
                }}
                rightIcon={<MdArrowForwardIos />}
              >
                Sortiment
              </Button>
              </Link>
              <Link href="/o-nas">
              <Button
                variant="filled"
                size="xl"
                radius="sm"
                sx={{
                  color: "black",
                  borderColor: "white",
                  backgroundColor: "white",
                  width: "12vw",
                  minWidth: "fit-content",
                }}
              >
                O nás
              </Button>
              </Link>
            </div>
          </section>
          <section className={styles.secondSection_laptop}>
           <OnasLaptop />
          </section>
          <section className={styles.thirdSection_laptop}>
            <SortimentLaptop />
          </section>
          <section className={styles.fourthSection_laptop}>
            <AktualityLaptop />
          </section>
          <section className={styles.fifthSection_laptop}>
            <KdeLaptop />
          </section>
        </div>
      </Media>
      <Media between={["zero", "tablet"]}>
        <div className={styles.main_mobile}>
          <section className={styles.firstSection_mobile}>
            <NavBar backgroundColor="transparent" />
            <Media between={["zero", "mobile"]}>
            <Text
              size="xl"
              sx={{ color: "#C4C4C4", fontSize: "13vw", marginTop: "10vh" }}
            >
              Vinařství
            </Text>
            <Text
              size="xl"
              sx={{ color: "#C4C4C4", fontSize: "20vw"}}
            >
              Badinovi
            </Text>
            <div
              style={{
                display: "flex",
                gap: "10%",
                justifyContent: "center",
                marginTop: "10%",
                paddingBottom: "5%",
              }}
            >
              <Link href="/sortiment">
              <Button
                variant="outline"
                size="xl"
                radius="sm"
                sx={{
                  color: "white",
                  borderColor: "white",
                  width: "12vw",
                  minWidth: "min-content",
                }}
                rightIcon={<MdArrowForwardIos />}
              >
                <Text sx={{fontsize: "10vw"}}>Sortiment</Text>
              </Button>
              </Link>
              <Link href="/o-nas">
              <Button
                variant="filled"
                size="xl"
                radius="sm"
                sx={{
                  color: "black",
                  borderColor: "white",
                  backgroundColor: "white",
                  width: "12vw",
                  minWidth: "min-content",
                  padding: "fit-content"
                }}
              >
                <Text sx={{fontsize: "10vw"}}>O nás</Text>
              </Button>
              </Link>
            </div>
            </Media>
            <Media between={["mobile", "tablet"]}>
            <Text
              size="xl"
              sx={{ color: "#C4C4C4", fontSize: "10vw", marginTop: "7vh" }}
            >
              Vinařství
            </Text>
            <Text
              size="xl"
              sx={{ color: "#C4C4C4", fontSize: "15vw"}}
            >
              Badinovi
            </Text>
            <div
              style={{
                display: "flex",
                gap: "10%",
                justifyContent: "center",
                marginTop: "10%",
                paddingBottom: "5%",
              }}
            >
              <Link href="/sortiment">
              <Button
                variant="outline"
                size="xl"
                radius="sm"
                sx={{
                  color: "white",
                  borderColor: "white",
                  width: "30vw",
                  minWidth: "min-content",
                  height: "10vh"
                }}
                rightIcon={<MdArrowForwardIos />}
              >
                Sortiment
              </Button>
              </Link>
              <Link href="/o-nas">
              <Button
                variant="filled"
                size="xl"
                radius="sm"
                sx={{
                  color: "black",
                  borderColor: "white",
                  backgroundColor: "white",
                  width: "20vw",
                  width: "30vw",
                  minWidth: "min-content",
                  height: "10vh",
                }}
              >
                O nás
              </Button>
              </Link>
            </div>
            </Media>
          </section>
          <section className={styles.secondSection_mobile}>
           <OnasMobile />
          </section>
          <section className={styles.thirdSection_mobile}>
           <SortimentMobile />
          </section>
          <section className={styles.fourthSection_mobile}>
            <AktualityMobile />
          </section>
          <section className={styles.fifthSection_mobile}>
            <KdeMobile />
          </section>
        </div>
      </Media>
      <Footer />
    </>
  );
}
